### ISSUE TITLE
spawn UNKNOWN

### ISSUE THREAD

**Issue by broerse** [abuiles/ember-watson#110]
Following https://emberjs.com/deprecations/v2.x/#toc_code-ember-k-code results in `spawn UNKNOWN
`
```
C:\dev\ember-pouch>ember install ember-watson
Installed packages for tooling via npm.
Installed addon package.

C:\dev\ember-pouch>ember watson:remove-ember-k --empty
spawn UNKNOWN
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at EmberWatson.removeEmberK (C:\dev\ember-pouch\node_modules\ember-watson\lib\formulas\remove-ember-k.js:12:3)
    at CoreObject.run (C:\dev\ember-pouch\node_modules\ember-watson\lib\commands\remove-ember-k.js:16:12)
    at CoreObject.<anonymous> (C:\dev\ember-pouch\node_modules\ember-cli\lib\models\command.js:224:19)
    at tryCatch (C:\dev\ember-pouch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\dev\ember-pouch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at C:\dev\ember-pouch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:628:16
    at flush (C:\dev\ember-pouch\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2373:5)
```

**Comment by bahdvp** [comment]
Same issue here:

`$ ember watson:remove-ember-k --return-empty
The option '--return-empty' is not registered with the watson:remove-ember-k command. Run `ember watson:remove-ember-k --help` for a list of supported options.
spawn UNKNOWN
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at EmberWatson.removeEmberK (C:\Users\eRule\git\regs-ember\node_modules\ember-watson\lib\formulas\remove-ember-k.js:12:3)
    at Class.run (C:\Users\eRule\git\regs-ember\node_modules\ember-watson\lib\commands\remove-ember-k.js:16:12)
    at resolve (C:\Users\eRule\git\regs-ember\node_modules\ember-cli\lib\models\command.js:238:20)
    at initializePromise (C:\Users\eRule\git\regs-ember\node_modules\rsvp\dist\rsvp.js:589:5)
    at new Promise$1 (C:\Users\eRule\git\regs-ember\node_modules\rsvp\dist\rsvp.js:1077:33)
    at Class.validateAndRun (C:\Users\eRule\git\regs-ember\node_modules\ember-cli\lib\models\command.js:194:12)
    at Promise.resolve.then.then (C:\Users\eRule\git\regs-ember\node_modules\ember-cli\lib\cli\cli.js:163:24)
`

**Comment by bahdvp** [comment]
Same issue. No resolution?

**Comment by knownasilya** [comment]
Give https://github.com/abuiles/ember-watson/pull/111 a try

**Comment by knownasilya** [comment]
The fix is now in master.

**Comment by bahdvp** [comment]
Cheers

**Comment by knownasilya** [comment]
Published v0.9.0

**Comment by broerse** [comment]
Thanks!

**Comment by yogendra-atcs** [comment]
Hi,
I am using "ember-watson": "0.9.0" but still getting same error. 
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\ember-cli\lib\models\addon.js:1641:27)
spawn UNKNOWN
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:369:9)
    at EmberWatson.removeEmberK (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\ember-watson\lib\formulas\remove-ember-k.js:13:3)
    at Class.run (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\ember-watson\lib\commands\remove-ember-k.js:16:12)
    at resolve (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\ember-cli\lib\models\command.js:317:20)
    at initializePromise (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\rsvp\dist\lib\rsvp\-internal.js:240:5)
    at new Promise (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\rsvp\dist\lib\rsvp\promise.js:143:33)
    at Class.validateAndRun (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\ember-cli\lib\models\command.js:269:12)
    at Promise.resolve.then.then (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\ember-cli\lib\cli\cli.js:162:24)
    at tryCatch (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\rsvp\dist\lib\rsvp\-internal.js:198:12)
    at invokeCallback (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\rsvp\dist\lib\rsvp\-internal.js:211:13)
    at publish (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\rsvp\dist\lib\rsvp\-internal.js:181:7)
    at flush (C:\Workspace\dev-all-ui-branch\dev\netstar-portal-ui\node_modules\rsvp\dist\lib\rsvp\asap.js:80:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

**Comment by yogendra-atcs** [comment]
Hi Ilya Radchenko,

I am waiting for your response.please reply on it..

**Comment by knownasilya** [comment]
@yogendra-atcs looks like the issue is also in the related codemod, I've filed an issue there.

**Comment by yogendra-atcs** [comment]
Thanks for reply..
