### ISSUE TITLE
Cannot find module './convert-tests-to-async-await'

### ISSUE THREAD

**Issue by IgorKvasn** [abuiles/ember-watson#113]
I upgraded to the newest ember-watson 0.9.0, but after I try to start `ember serve` I am getting this error message:
```
Cannot find module './convert-tests-to-async-await'
Error: Cannot find module './convert-tests-to-async-await'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kvasnicka/Data/watson-test/node_modules/ember-watson/lib/commands/index.js:16:48)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by knownasilya** [comment]
Should be resolved with v0.9.1
