### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode installing SASS node package

### ISSUE THREAD

**Issue by renepf** [abuiles/ember-watson#118]
Trying to install LESS/SASS. And getting this error after installing node.js in Linux 16.04.
Installed LESS compiler

Followed these steps:

1. sudo apt-get install node.js
2. sudo apt-get update  
3. sudo apt-get upgrade
4. sudo apt-get install npm - node packet manager
5. sudo npm install -g less  
6. sudo npm install node-sass -g (dind't work)
7. tried: sudo gem install sass 

Then I got this error
Error
`$sudo npm update npm -g 
/usr/local/lib/node_modules/npm/bin/npm-cli.js:82
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`
Since then I can basically do nothing anymore. Not event do simple command like 'npm -v'.

Could you please help me?

**Comment by knownasilya** [comment]
That should be fixable by using a newer version of node
