### ISSUE TITLE
convert-resource-router-mapping: undefined is not a function

### ISSUE THREAD

**Issue by jcope2013** [abuiles/ember-watson#56]
```
ember watson:convert-resource-router-mapping app/router.js 
version: 0.2.7
undefined is not a function
TypeError: undefined is not a function
    at Class.module.exports.run (/Users/jc/id/node_modules/ember-watson/addon/commands/convert-resource-router-mapping.js:15:12)
    at Class.<anonymous> (/Users/jc/id/node_modules/ember-cli/lib/models/command.js:136:17)
    at lib$rsvp$$internal$$tryCatch (/Users/jc/id/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jc/id/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/jc/id/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/jc/id/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by abuiles** [comment]
@jcope2013 what happens if you run it without the file? (it defaults to app/router.js anyways) cc @marcioj

**Comment by jcope2013** [comment]
@abuiles same issue

**Comment by abuiles** [comment]
@jcope2013 just released ember-watson@0.5.7 which includes a fix for this issue, thanks for reporting!

**Comment by albertpak** [comment]
I'm on Ember 1.13.8, using `"ember-watson": "^0.6.6",` I ran `ember watson:convert-resource-router-mapping app/router.js` while in ember folder, but got no output - no errors and etc - did i give it wrong command?

**Comment by marcioj** [comment]
@albertpak the command doesn't display anything if there is nothing to do.
Do you have any occurrence of `this.resource` in your `app/router.js` file?

**Comment by SamvelRaja** [comment]
@marcioj [PR](https://github.com/abuiles/ember-watson/pull/86) would avoid such issues.
